package com.blogsite.userservice.dto;

import com.blogsite.userservice.model.User;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * ========================================
 * USER RESPONSE DTO
 * ========================================
 * 
 * This is what the API sends back to the client after registration.
 * 
 * NOTICE:
 * - We DON'T include the password (security!)
 * - We DO include: id, userName, email, timestamps
 * 
 * This is the Builder pattern (Creational Design Pattern) in action!
 * 
 * BUILDER PATTERN:
 * Instead of: new UserResponse(1L, "John", "john@example.com", ...)
 * You can do:
 * UserResponse.builder()
 * .id(1L)
 * .userName("John")
 * .userEmail("john@example.com")
 * .createdAt(LocalDateTime.now())
 * .build();
 * 
 * WHY USE BUILDER?
 * - More readable
 * - Can set fields in any order
 * - Don't need to remember parameter order
 * - Can omit optional fields
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserResponse {

    /**
     * User ID - generated by database
     */
    private Long id;

    /**
     * User's username
     */
    private String userName;

    /**
     * User's email
     */
    private String userEmail;

    /**
     * When the user account was created
     */
    private LocalDateTime createdAt;

    /**
     * Success message (optional)
     */
    private String message;

    /**
     * FACTORY METHOD - Another Creational Design Pattern!
     * 
     * This static method creates a UserResponse from a User entity.
     * It's called a "factory" because it manufactures objects.
     * 
     * HOW TO USE:
     * User user = userRepository.save(newUser);
     * UserResponse response = UserResponse.fromEntity(user);
     * 
     * @param user The User entity to convert
     * @return UserResponse DTO ready to send to client
     */
    public static UserResponse fromEntity(User user) {
        return UserResponse.builder()
                .id(user.getId())
                .userName(user.getUserName())
                .userEmail(user.getUserEmail())
                .createdAt(user.getCreatedAt())
                .message("User registered successfully!")
                .build();
    }
}
